name: LLIO CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env: ${{ matrix.config.env }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "MacOS 10.15",
            os: macos-10.15,
            env: [ CMAKE_CONFIGURE_OPTIONS: "" ],
            artifact: "llfio-v2.0-binaries-darwin64-${{ github.sha }}.tgz"
          }
          
    steps:
    - uses: actions/checkout@v2
    
    - name: "cmake tests (error code)"
      run: ctest -S .ci.cmake -VV --timeout 300 -DCTEST_CONFIGURE_OPTIONS=$CMAKE_CONFIGURE_OPTIONS
